WIN_WIDTH, WIN_HEIGHT = 1600, 800

IMG_SIZE = 40  # pixel
GAP = IMG_SIZE - 4  # pixel
BOX_SIZE = 24
BOX_GAP = 24
BOX_OFFSET = (IMG_SIZE - BOX_SIZE) // 2

BULLET_VELOCITY = 10  # pixel
PLAYER_VELOCITY = 4  # pixel
GUARD_VELOCITY = 4

BULLET_COOLDOWN = 0.2  # sec
KEY_COOLDOWN = 0.5

PAUSE_KEY_COOLDOWN = 0.1